// Generated by CoffeeScript 1.12.2
(function() {
  angular.module('DemoApp').factory('S3', [
    '$q', function($q) {
      return {
        list: function(bucketName) {
          var filesDefer;
          filesDefer = $q.defer();
          AWS.config.region = 'eu-central-1';
          AWS.config.credentials = new AWS.CognitoIdentityCredentials({
            IdentityPoolId: 'eu-central-1:68658909-d15f-4579-a7cb-b1d61670e7ce'
          });
          new AWS.S3().listObjects({
            Bucket: bucketName
          }, function(err, data) {
            console.log("yay!!! with " + (JSON.stringify(data)));
            if (err != null) {
              console.log("error: " + err);
              return filesDefer.reject(err);
            } else {
              return filesDefer.resolve(data.Contents);
            }
          });
          return filesDefer.promise;
        }
      };
    }
  ]);

}).call(this);
