// Generated by CoffeeScript 1.12.3
(function() {
  var S3Client, s3Client;

  S3Client = (function() {
    function S3Client() {
      AWS.config.region = 'eu-central-1';
      AWS.config.credentials = new AWS.CognitoIdentityCredentials({
        IdentityPoolId: 'eu-central-1:68658909-d15f-4579-a7cb-b1d61670e7ce'
      });
      this.s3 = new AWS.S3();
    }

    S3Client.prototype.client = function() {
      return this.s3;
    };

    return S3Client;

  })();

  s3Client = new S3Client().client();

  angular.module('DemoApp').factory('S3', [
    '$q', function($q) {
      return {
        list: function(bucketName, prefix) {
          var filesDefer;
          filesDefer = $q.defer();
          s3Client.listObjects({
            Bucket: bucketName,
            Prefix: prefix
          }, function(err, data) {
            if (err != null) {
              console.log("error: " + err);
              return filesDefer.reject(err);
            } else {
              return filesDefer.resolve(data.Contents);
            }
          });
          return filesDefer.promise;
        },
        downloadLink: function(bucketName, objectName) {
          return s3Client.getSignedUrl('getObject', {
            Bucket: bucketName,
            Key: objectName,
            Expires: 300
          });
        }
      };
    }
  ]);

}).call(this);
